// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABzie_eJYQ1Vy8OO4k7aMVugVrzfYpBoQ',
    appId: '1:430690791393:android:f4e6dec4769523669d6ca0',
    messagingSenderId: '430690791393',
    projectId: 'oryzn-3c0b7',
    storageBucket: 'oryzn-3c0b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ZJaZoGgvBCR9J1XMfxpt4s6Zi6vdZjI',
    appId: '1:430690791393:ios:41e7ce95e62535149d6ca0',
    messagingSenderId: '430690791393',
    projectId: 'oryzn-3c0b7',
    storageBucket: 'oryzn-3c0b7.firebasestorage.app',
    androidClientId: '430690791393-d23ej7o3jqo4t1pcj4rdcno9i1jth6v8.apps.googleusercontent.com',
    iosClientId: '430690791393-95e3dsjv507hb7sadg6ii624f66jdvm2.apps.googleusercontent.com',
    iosBundleId: 'com.oryzn.app',
  );

}